tunnel: brainsait-claims
credentials-file: /home/ec2-user/.cloudflared/3d82864a-6a9c-4eb1-afd7-eb2f111ca62f.json

ingress:
  # Home page (landing)
  - hostname: claims-home.brainsait.com
    service: http://localhost:80
  
  # Claims management (main app)
  - hostname: claims.brainsait.com
    service: http://localhost:8082
  
  # Dashboard
  - hostname: dashboard.brainsait.com
    service: http://localhost:8081
  
  # API
  - hostname: api.brainsait.com
    service: http://localhost:3001
  
  # Health monitoring
  - hostname: health.brainsait.com
    service: http://localhost:8080
  
  # Catch-all
  - service: http_status:404
